### ISSUE TITLE
Co2 values round 400 whatever I do

### ISSUE THREAD

**Issue by KlausHB** [miguel5612/MQSensorsLib#34] opened 2020-09-26 20:45 UTC
Hi,

by now I did no calibrating, but smoking in front of the MQ-135, putting a candle in a glas, breathing to the sensor etc. makes almost no difference to the Co2 value. It's always around 400.

Are You sure that You made the correct calculation?

Greetings

Klaus

**Comment by miguel5612** [comment] 2022-02-06 22:11
Best regards KlausHB,
Sorry for the delay in replying, first of all regarding the calibration we have followed the datasheet so I think it is correct (you can still check the whole process).
To verify the process:
1. Open the datasheet which in your case is:
https://www.electronicoscaldas.com/datasheet/MQ-135_Hanwei.pdf
2. Locate the Rs/R0 graph (page 2 of the datasheet).
3. Cut out the graph and save it on your computer.
4. Use the tool to estimate the values empirically:
https://automeris.io/WebPlotDigitizer/
5. Use excel to estimate the values of a and b, doing a regression. Examples are here:
https://www.youtube.com/watch?v=aw-GluLZIWA
6. Try, in the same excel that you have calculated now give values to Rs/R0 and calculate the values in PPM (this way you can check the quality of your results).
7. Document, make a small report of what you have done so far.
8. Using the values of A and B provided in the library in the file:
https://github.com/miguel5612/MQSensorsLib/blob/master/examples/MQ-135-ALL/MQ-135-ALL.ino
Test again, replacing the values of Rs/R0 using your values and the values already in the library. Compare how much the results deviate and which is the closest.
9. If there is more than 10% deviation between your values and the values calculated with the library's A and B values, create an issue uploading the values calculated by you together with the documents you elaborated in point 7 (ideally a test with which I can verify how you calculated the A and B values using the datasheet).

I remain attentive, if we can improve of course we can update the library.

Or if it is ok, please confirm it as well since in our tests it has given good results :).

I will close this issue assuming that this answer clarifies your initial concern, if not I appreciate you open a new one :D

**Closed by miguel5612** 2022-02-06 22:11 UTC
